### PR TITLE
Make it possible to use pkgutils library on Linux and install to custom destination

### PR DESCRIPTION
**Pull request by ids1024**
For a bootstrap tool I am working on.

### CODE REVIEW

**Comment by ids1024** [comment]
Here is the tool I've been working on: https://github.com/ids1024/redox-bootstrap

The point is to build a base system from packages, either by downloading them from the remote repository, or building from a local copy of the cookbook.

**Comment by jackpot51** [comment]
Thank you so much! This is very important for building Redox with the cookbook

**Comment by jackpot51** [comment]
Did you see the installer? You might want to put your work there

**Comment by jackpot51** [comment]
https://github.com/redox-os/installer

**Comment by ids1024** [comment]
Ah yes, it probably should go in the installer.

**Comment by ids1024** [comment]
redox-os/installer#2

**Comment by jackpot51** [comment]
Major woot

**Pull request merged**
